# -*- coding: utf-8 -*-
"""Soru1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqNEcfDeDXbalKhrDEC5Ym8Hd724Y0yJ
"""

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Colab ortamında ses oynatmak için
from IPython.display import Audio

from google.colab import drive
drive.mount('/content/drive')
dosya_yolu = '/content/drive/MyDrive/UrbanSound8K/fold1/7061-6-0-0.wav'

# Ses dosyasını yükleme
data, sr = librosa.load(dosya_yolu, sr=None) # sr=None, dosyanın orijinal örnekleme hızını korur

# Teknik özellikleri hesaplama
sure_saniye = len(data) / sr
kanal_sayisi = 1 # librosa, varsayılan olarak sesi mono (tek kanal) yükler.
dtype = data.dtype

print("--- Ses Dosyasının Teknik Özellikleri ---")
print(f"1. Seçilen Dosya: {dosya_yolu}")
print(f"2. Örnekleme Oranı (sr): {sr} Hz")
print(f"3. Süre (saniye cinsinden): {sure_saniye:.3f} saniye")
print(f"4. Toplam Örnek Sayısı (Frame): {len(data)}")
print(f"5. Kanal Sayısı: {kanal_sayisi} (Mono)")
print(f"6. Veri Tipi (Bit Derinliği): {dtype}")

print("\n--- data ve sr Değişkenlerinin İncelemesi ---")
print(f"data değişkeninin Türü (Type): {type(data)}")
print(f"data değişkeninin Şekli (Shape): {data.shape}")
print(f"sr değişkeninin Türü (Type): {type(sr)}")
print(f"sr değişkeninin Değeri: {sr}")