# -*- coding: utf-8 -*-
"""Soru3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flxZM8vtmG6LFSVghhfnBvyTeZEBcO5c
"""

import librosa
import librosa.display
import matplotlib.pyplot as plt
from IPython.display import Audio
import numpy as np

from google.colab import drive
drive.mount('/content/drive')
URBANSOUND_YOLU = '/content/drive/MyDrive/UrbanSound8K/'

ses_dosyalari = {
    "Köpek (classID=1)": f"{URBANSOUND_YOLU}fold5/86284-3-0-0.wav",
    "Karışık (classID=0)": f"{URBANSOUND_YOLU}fold1/97317-2-0-23.wav",
    "Silah Sesi (classID=6)": f"{URBANSOUND_YOLU}fold1/7061-6-0-0.wav",
    "Karışık Kedi Sesi(classID=7)": f"{URBANSOUND_YOLU}fold10/22973-3-0-2.wav",
}

veri_seti = {}
for etiket, yol in ses_dosyalari.items():
    try:
        # sr=44100 olarak sabitleme veya sr=None kullanma tercih edilebilir.
        y, sr = librosa.load(yol, sr=44100)
        veri_seti[etiket] = {'y': y, 'sr': sr}
        print(f"✅ {etiket} dosyası başarıyla yüklendi.")
    except Exception as e:
        print(f"❌ HATA: {etiket} dosyası yüklenemedi. Yol: {yol}. Hata: {e}")
        veri_seti[etiket] = None # Hata durumunda boş bırak

# Görselleştirmeyi 4 alt grafik (subplot) üzerinde yapma
fig, axes = plt.subplots(len(veri_seti), 1, figsize=(15, 18))
plt.tight_layout(pad=5.0) # Grafikler arası boşluk

i = 0
for etiket, veri in veri_seti.items():
    if veri is None:
        continue # Yüklenemeyen dosyayı atla

    y = veri['y']
    sr = veri['sr']

    # 1. STFT (Spektrogram) hesaplama
    # D: Genlik Spektrogramı. np.abs(D) ile genlik alınıyor.
    D = librosa.stft(y)
    # Ses enerjisinin daha iyi gözlemlenmesi için dB (desibel) ölçeğine dönüştürme
    S_db = librosa.amplitude_to_db(np.abs(D), ref=np.max)

    # 2. Spektrogramı çizdirme
    librosa.display.specshow(S_db, sr=sr, x_axis='time', y_axis='hz', ax=axes[i])
    axes[i].set(title=f'Zaman-Frekans Grafiği (Spektrogram) - Sınıf: {etiket}')
    axes[i].set_xlabel('Zaman (s)')
    axes[i].set_ylabel('Frekans (Hz)')

    # 3. Ses dosyasını çalma kodu
    print(f"\n--- Sınıf: {etiket} ---")
    print(f"Ses Dosyası Oynatılıyor: (Süre: {len(y)/sr:.2f} s)")
    display(Audio(data=y, rate=sr)) # Colab/Jupyter'da ses oynatma

    i += 1

plt.show()