# -*- coding: utf-8 -*-
"""Soru5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lj4jETaz2HhFEbAK2yIb7YKSyR_aFDOm
"""

import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Audio, display
import os

from google.colab import drive
drive.mount('/content/drive')
dosya_yolu = '/content/drive/MyDrive/UrbanSound8K/fold1/7061-6-0-0.wav'

# 1. Ses dosyasını yükleme
# Mel-spektrogram için standart bir sr (22050) kullanmak en iyisidir.
TARGET_SR = 22050
y, sr = librosa.load(dosya_yolu, sr=TARGET_SR)
print(f"Yüklenen dosya: {dosya_yolu.split(os.sep)[-1]} | Örnekleme Hızı (sr): {sr} Hz")

# 2. Mel-Spektrogram Özniteliklerini Çıkarma
# n_mels=128, Mel bandının sayısını belirler (yaygın kullanılan değer)
mels = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)
mels_db = librosa.power_to_db(mels, ref=np.max) # Enerjiyi logaritmik (dB) ölçeğe dönüştürme

print("-" * 50)

print("--- Sayısal İncelenme ---")
print(f"Mel-Spektrogram Matrisinin Şekli (Shape): {mels_db.shape}")
print(f"Matrisin Veri Tipi (Dtype): {mels_db.dtype}")
print("\nMel-Spektrogram (dB) Matrisinin İlk 3 satır ve 5 sütunu:")
# Matrisin üst sol köşesini yazdırma (Frekans ekseninde ilk 3 bant, Zaman ekseninde ilk 5 frame)
print(mels_db[:3, :5])

# 1. Mel-Spektrogramı görselleştirme
plt.figure(figsize=(12, 4))
librosa.display.specshow(mels_db, x_axis='time', y_axis='mel', sr=sr, fmax=sr/2)
plt.colorbar(format='%+2.0f dB')
plt.title('Mel-Spektrogram')
plt.tight_layout()
plt.show()

# 2. Ses dosyasını çalma
print("\n--- Ses Dosyası Oynatılıyor ---")
display(Audio(y, rate=sr))