# -*- coding: utf-8 -*-
"""Soru2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U1yWHLOGjewBPKADfuVyNnsI99JCbJmJ
"""

import matplotlib.pyplot as plt
import librosa.display
import numpy as np

from google.colab import drive
drive.mount('/content/drive')
dosya_yolu = '/content/drive/MyDrive/UrbanSound8K/fold1/7061-6-0-0.wav'
data, sr = librosa.load(dosya_yolu, sr=None)

# Grafiği çizdirme
plt.figure(figsize=(14, 5))
librosa.display.waveshow(y=data, sr=sr, x_axis='time')
plt.title(f'Zaman-Genlik Grafiği (Waveform) - Örnek Dosya')
plt.xlabel('Zaman (Saniye)')
plt.ylabel('Genlik (Amplitude)')
plt.grid(True)
plt.show()

# Gerekli kütüphane: IPython.display
from IPython.display import Audio

print("Ses Dosyasını Oynatılıyor:")
Audio(data=data, rate=sr)
